### ISSUE TITLE
[LUA] Missing features for the original campaign

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1177]
This issue links all issues / features that need to be fixed for the original campaign
- [ ] #743 - AI agression level
- [ ] #568 - Campaign Screen
- [ ] #1175 - MET_LAND_SIZE
- [ ] #1176 - Change agression level on attack

**Comment by Spikeone** [comment]
I've uploaded the updated (and original) map files and the lua scripts here: https://github.com/Spikeone/RttR_Campaigns
