### ISSUE TITLE
[Trade] Bugs of trade Addon

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#131]
- [x] #224 Caravan uses strange "highways"
- [x] #223 Caravan dies
- [x] #222 Trade sometimes shows 0 for max amount
- [x] #221 Trade window has wrong shadow position

**Comment by Spikeone** [comment]
Has anybode checked the code by Robert Schade?

**Comment by Spikeone** [comment]
https://bugs.launchpad.net/s25rttr/+bug/899108

Beheben einiger Bugs, prüfen der vorhandenen Eseln u.s.w.
http://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=903&start=-1#8916

**Comment by Spikeone** [comment]
https://bugs.launchpad.net/s25rttr/+bug/963433

Beim Handeln von Siedlern zwischen 2 verbündeten Lagerhäusern kommen nicht alle Siedler an.

Ich habe einmal 10 Generäle (GF 168000) und einmal 15 Generäle (GF 176000) zu meinem Verbündeten geschickt.

Als ich die 10 Generäle schickte, liefen sie über das Gebirge und irgendwann teleportierte sich die Karawane an eine andere Stelle, aber dann war nurnoch 1 General übrig.

Das Selbe beim zweiten Mal:
Ich sendete 15 Generäle und nur 4 Generäle kamen wirklich an. Sie liefen den selben Weg wie vorher und teleportierten sich quasi auch an eine andere Stelle im Gebirge.

Savegame und Replay befindet sich im Anhang (rev 7891)

Para (sit) wrote on 2012-03-23:	#1
Savegame + Replay Edit (758.9 KiB, application/zip)

Spike (fvv1) wrote on 2012-06-29:	#2
Soweit ich bemerkt habe liegt es an diesen "Autobahnen" denn manchmal rennen die Leute auch einfach ins Wasser um zu sterben.

**Comment by Spikeone** [comment]
https://bugs.launchpad.net/s25rttr/+bug/366861

Trading between different players is sometimes very important. There can be a lot of ways how to trade, just a market, the warehouse, the harbor or a donkey-caravan can be used for this. Using a warehouse with the caravan and the harbor with the ships is the simplest solution because a trading menu could be included in the buildings directly with an own page.

Simon (simon-r) wrote on 2009-08-02:	#1
Another possibility is the connection of ally-territorys with roads. In an additional menu one can control which goods can pass the border.
This is, of course, only possible if the territorys tangent each other.

Tombus (tombus) wrote on 2011-08-16:	#2
I propose to replace the helpe to scoutin caravana. It would be more logical, because the scout who knows the way;)

Para (sit) wrote on 2011-08-28:	#3
i agree with tombus idea, it would be better if it is a scout :)

**Comment by Flamefire** [comment]
Preview zu der GUI von Robert Shade: <br><a href="http://www.directupload.net/file/d/4082/brgj9ulb_png.htm" target="_blank"><img src="http://fs1.directupload.net/images/150817/temp/brgj9ulb.png" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

**Comment by Flamefire** [comment]
Please clear this bug from any feature request and split it into smaller bugs.

--> #216 #217
