### ISSUE TITLE
[Trade] Improvements (current version)

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#225]
- [ ] #216 Improve GUI
- [ ] #217 Option to return donkeys
- [ ] #218 Use scout as caravan leader
- [ ] #219 Water in trade menu shown twice
